### PR TITLE
Rework `test_utils`

### PR DESCRIPTION
**Pull request by sandreae**
Overhaul of `test_utils`.

Depends on: https://github.com/p2panda/p2panda/pull/343

## Goals:
- tidy up and streamline test fixtures and templates
- have fewer, more useful methods/fixtures
- make it possible to import fixtures into other crates (`aquadoggo`)
- delete code :balloon: :1st_place_medal: 
- refactor `node` to use `StorageProvider` <-- next PR

New folder structure: 

```sh
├── constants.rs
├── fixtures
│   ├── document_fixtures.rs
│   ├── entry_fixtures.rs
│   ├── hash_fixtures.rs
│   ├── identity_fixtures.rs
│   ├── mod.rs
│   ├── operation_fixtures.rs
│   ├── schema_fixtures.rs
│   └── version_fixtures.rs
├── generate_test_data.rs
├── mocks
│   ├── client.rs
│   ├── constants.rs
│   ├── logs.rs
│   ├── mod.rs
│   ├── node.rs
│   └── utils.rs
├── mod.rs
├── README.md
├── templates
│   ├── entry_templates.rs
│   ├── mod.rs
│   ├── operation_templates.rs
│   └── version_fixture_templates.rs
├── test_data
│   ├── json_data.rs
│   └── mod.rs
└── utils.rs
```

## Todo
- [x] place all test utils behind `testing` feature flag
- [x] restructure fixtures module
- [x] refactor fixtures
- [x] restructure templates module
- [x] refactor templates
- [x] remove all fixtures and test methods from `utils`
- [x] ~~only use `defaults` for templates~~ <-- actually managed to remove the defaults folder completely

## Next Steps (separate PR)
- [ ] review naming in `constants.rs`
- [ ] review all doc strings
- [ ] more templates
- [ ] refactor `Node` to use `StorageProvider`

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header
- [x] Check if descriptions and terminology match `handbook` content (and visa-versa)

### CODE REVIEW

**Comment by sandreae** [comment]
sadly, the test coverage actually decreases with this pr :rofl: BUT I think it's just cos I deleted some code...

**Review by adzialocha — APPROVED** [review]
Amazing! This is such a fantastic refactor / clean-up! Will be really cool to be able to use it in `aquadoggo` (think I can need it for the materialization tasks) :+1:

Will the generate-cbor-data binary be deleted as well (as a future issue)? Its not really needed anymore since we don't use JSON RPC, right?

**Comment by sandreae** [comment]
> (think I can need it for the materialization tasks)

Yeh, writing that little bit of materialiser code is what made me want to access the fixtures badly in the first place.

**Comment by sandreae** [comment]
> Will the generate-cbor-data binary be deleted as well (as a future issue)? Its not really needed anymore since we don't use JSON RPC, right?

Yes, good shout!!

**Comment by sandreae** [comment]
I updated the doc string examples, please check them out :heart: I'm gunna merge :+1:

**Pull request merged**
