### PR TITLE
add dev deps

### PR DESCRIPTION
**Pull request by nichoth**
Still trying to get the test to run, but this is a start

### CODE REVIEW

**Comment by cafca** [comment]
Hey @nicoth! As a gratitude for making the first ever unexpected p2panda PR you receive a complementary emoji cake 🎂 :) I'm on the go right now but this looks reasonable? I'm a bit confused why `wasm-pack` wasn't in the deps before. It feels like there was a reason for it because it's so. obviousbut I don't see it now.

**Comment by adzialocha** [comment]
> I'm a bit confused why `wasm-pack` wasn't in the deps before. It feels like there was a reason for it because it's so. obviousbut I don't see it now. 

Do we use the `wasm-pack` as a npm package? I think it's the Rust binary which needs to be installed via 
https://rustwasm.github.io/wasm-pack/installer/

Or does the npm package use it for you? Then I'm fine with adding it as a dependency 👍 in any case we should definitely add some steps to the README.md

Also, @nichoth what errors do you get?

**Comment by adzialocha** [comment]
Maybe related: we have issues with installing all dependencies using Linux (Ubuntu, Arch) and Node v15, with v11 and v12 it works

**Comment by nichoth** [comment]
Thanks I wasn't sure how maintained this was

From the `p2panda-js` directory, if I do `npm test` from my fork, this is the result:

```
p2panda-js(main) nick$ npm test

> p2panda-js@0.1.0 test
> run-s clear test:prepare test:mocha


> p2panda-js@0.1.0 clear
> rimraf ./lib/* ./wasm-web/* ./wasm-node/*


> p2panda-js@0.1.0 test:prepare
> run-s --silent wasm webpack:node

Error: No such file or directory (os error 2)
ERROR: "test:prepare" exited with 1.
```

**Comment by sandreae** [comment]
Hi @nichoth, thanks for trying things out and opening this PR.

I just tried setting up a fresh local repo to see if I got the same behavior. With node v15.13.0 then running `npm i` and `npm run test` i get successful test execution. 

It could be to do with not having the correct `rust` dependencies? The step of the test suite that fails is the wasm build step from the rust library (i think....).

**Comment by sandreae** [comment]
To clarify, I did my fresh repo setup from the main branch, not this PR.

**Comment by nichoth** [comment]
Thanks. So I installed rust, and now there is a new error

```
p2panda-js(main) nick$ npm test

> p2panda-js@0.1.0 test
> run-s clear test:prepare test:mocha


> p2panda-js@0.1.0 clear
> rimraf ./lib/* ./wasm-web/* ./wasm-node/*


> p2panda-js@0.1.0 test:prepare
> run-s --silent wasm webpack:node

    Finished release [optimized] target(s) in 0.20s
    Finished release [optimized] target(s) in 0.20s
node:
  1 asset
  4 modules

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts(1,24)
        TS2307: Cannot find module 'wasm-web/index_bg.wasm' or its corresponding type declarations.

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts(2,36)
        TS2307: Cannot find module 'wasm-web' or its corresponding type declarations.

  node (webpack 5.14.0) compiled with 2 errors in 3965 ms
ERROR: "test:prepare" exited with 1.
```

**Comment by nichoth** [comment]
Installed `wasm-web` --

```
$ npm i -S wasm-web
```

the current error
```
p2panda-js(main) nick$ npm test

> p2panda-js@0.1.0 test
> run-s clear test:prepare test:mocha


> p2panda-js@0.1.0 clear
> rimraf ./lib/* ./wasm-web/* ./wasm-node/*


> p2panda-js@0.1.0 test:prepare
> run-s --silent wasm webpack:node

    Finished release [optimized] target(s) in 0.20s
    Finished release [optimized] target(s) in 0.20s
node:
  1 asset
  4 modules

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts(1,24)
        TS2307: Cannot find module 'wasm-web/index_bg.wasm' or its corresponding type declarations.

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts(2,36)
        TS2307: Cannot find module 'wasm-web' or its corresponding type declarations.

  node (webpack 5.14.0) compiled with 2 errors in 3965 ms
ERROR: "test:prepare" exited with 1.
```

**Comment by sandreae** [comment]
Thanks for the new error report.

What does your `wasm-web` folder look like after the packages should have been compiled? It seems like something is still missing there. Mine looks like this:

wasm-web

**Comment by nichoth** [comment]
hmm yes the `wasm-web` folder is empty

```
p2panda-js(main) nick$ ls -a wasm-web/
.  ..
```

**Comment by sandreae** [comment]
Worth trying to build things on the [`p2panda-rs`](https://github.com/p2panda/p2panda/tree/main/p2panda-rs) side just to check everything is working there as expected.

**Comment by nichoth** [comment]
Interesting… I have never used rust, but i typed `cargo test` in the `p2panda-rs` directory, and a little while later I had green text for everything and it said everything passed the tests.

**Comment by sandreae** [comment]
Ok, good. And if you then run `wasm-pack build`?

**Comment by nichoth** [comment]
If I do `wasm-pack build` in the directory `p2panda-rs` it says 'command not found'

if I try it in `p2panda-js`, it says "Error: crate directory is missing a `Cargo.toml` file; is `.` the wrong directory?"

```
p2panda-js(main) nick$ pwd
/Users/nick/code/p2panda/p2panda-js
p2panda-js(main) nick$ npx wasm-pack build
Error: crate directory is missing a `Cargo.toml` file; is `.` the wrong directory?
```

**Comment by adzialocha** [comment]
Ah ok, you're trying to use the npm `wasm-pack` package! you need to remove this dependency and install `wasm-pack` via https://rustwasm.github.io/wasm-pack/installer/ - this will give you a global cargo binary you can run in the `p2panda-rs` folder. It's similar to the npm version, just with a different interface. I can also imagine it will fix your other problem, as we don't use the npm package 👍

**Comment by nichoth** [comment]
Ah ha thanks. I have never used rust before, just js/npm

**Comment by nichoth** [comment]
1. remove `wasm-pack` from npm 
```
$ npm rm -D wasm-pack
```

2. install `wasm-pack` via cargo/rust
```
$ curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
```

3. try `npm test` in `p2panda-js`

```
$ npm test

> p2panda-js@0.1.0 test
> run-s clear test:prepare test:mocha


> p2panda-js@0.1.0 clear
> rimraf ./lib/* ./wasm-web/* ./wasm-node/*


> p2panda-js@0.1.0 test:prepare
> run-s --silent wasm webpack:node

    Finished release [optimized] target(s) in 0.36s
    Finished release [optimized] target(s) in 0.50s
node:
  1 asset
  4 modules

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/index.ts
  ./src/index.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/index.ts(17,6)
        TS2349: This expression is not callable.
    Each member of the union type '(<TResult1 = typeof import("/Users/nick/code/p2panda/p2panda-js/lib/wasm/index"), TResult2 = never>(onfulfilled?: ((value: typeof import("/Users/nick/code/p2panda/p2panda-js/lib/wasm/index")) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | ... 1 ...' has signatures, but none of those signatures are compatible with each other.

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/index.ts
  ./src/index.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/index.ts(17,14)
        TS7031: Binding element 'setWasmPanicHook' implicitly has an 'any' type.

  ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts
  [tsl] ERROR in /Users/nick/code/p2panda/p2panda-js/src/wasm-adapter/browser.ts(1,24)
        TS2307: Cannot find module 'wasm-web/index_bg.wasm' or its corresponding type declarations.

  node (webpack 5.14.0) compiled with 3 errors in 9184 ms
ERROR: "test:prepare" exited with 1.

```

**Comment by nichoth** [comment]
hmm I guess this pull request is not relevant anymore, it's more like an issue of how to get the tests to run

**Comment by cafca** [comment]
We have [updated the documentation](https://github.com/p2panda/p2panda/commit/10dcd8847f8b7568991b69c6532de2005ae7cd47) to make clear that you need to install `wasm-pack`. Thanks for bringing this up @nichoth!

**Pull request closed without merging**
