### PR TITLE
Remove `aquamarine` and `serde_json`

### PR DESCRIPTION
**Pull request by sandreae**
Remove `aquamarine` and `serde_json`.

In se/de tests for `SchemaId` we now de/serialise to and from cbor bytes. 

closes: https://github.com/p2panda/p2panda/issues/298

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header
- [x] Check if descriptions and terminology match `handbook` content (and visa-versa)

### CODE REVIEW

**Review by adzialocha — COMMENTED** [review]
We could use the json crate completely, serialize to cbor instead and use the `cbor!` macro for readability 👍

**Comment by sandreae** [comment]
aaaaaand, it's gone!

**Comment by sandreae** [comment]
but I couldn't find a use for the `cbor!` macro (which I really wanted to) is there a different way you imagined this refactoring going?

**Review by adzialocha — APPROVED** [review]
> but I couldn't find a use for the `cbor!` macro (which I really wanted to) is there a different way you imagined this refactoring going?

I've had a go but it just creates more lines of code, so I think you're approach is better :+1:

Looks all good to me now, thanks for the clean-up!!

**Pull request merged**
