### PR TITLE
Extend `MessageFields` for WebAssembly

### PR DESCRIPTION
**Pull request by adzialocha**
* Add `add` method with type field to add Relation, Float, Integer and Boolean fields as well :warning: **Breaking Change!**
* Add method to read `length` of `MessageFields` instances
* Add methods to `get` and `remove` fields

Closes: #52 and #53

### CODE REVIEW

**Comment by cafca** [comment]
@adzialocha what do you think about making a `set` method with a `type` parameter instead of the separate methods for each type?

**Comment by adzialocha** [comment]
> @adzialocha what do you think about making a `set` method with a `type` parameter instead of the separate methods for each type? I was thinking about how we will be populating the fields based on type information from the schema definition later and that that might be more elegant with a type parameter.

Interesting idea, I'll have a look!

**Comment by adzialocha** [comment]
Ok, I think I have it @cafca, please have a look!

**Comment by adzialocha** [comment]
I've renamed the method to `add` again as it is a) consistent with how it is named in `p2panda-rs` b) `set` implies that you can just overwrite values when applying the method on the same field again which is not the case, it will actually throw an error when it is already given.

**Pull request merged**
