### PR TITLE
Use new `Operation` naming everywhere

### PR DESCRIPTION
**Pull request by sandreae**
We renamed "message" to "operation". Make this change in `p2panda-rs` and `p2panda-js`.

closes https://github.com/p2panda/p2panda/issues/134

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header

### CODE REVIEW

**Review by adzialocha — CHANGES_REQUESTED** [review]
Nice nice! I think it should still have a changelog entry though (actually literally every PR) 👍

Also, all of this smells very much like breaking changes? Probably something to note in the `CHANGELOG.md` as well :grin:

**Comment by sandreae** [comment]
Yes indeed. It breaks EVERYTHING.

**Comment by sandreae** [comment]
Do we have a convention for marking breaking changes in the CHANGELOG additions?

**Comment by sandreae** [comment]
I have this `aquadoggo` PR in progress https://github.com/p2panda/aquadoggo/pull/48 but I think there might be other breaking changes in the mix too...

**Comment by adzialocha** [comment]
> Do we have a convention for marking breaking changes in the CHANGELOG additions?

Not really yet, think for now it's enough to write it somewhere next to it, eventually when we do our first stable release we should have an own section for it.

**Review by adzialocha — APPROVED** [review]

**Review by cafca — APPROVED** [review]
I'm not going to read through all of this. But I'm really glad it's here! More clarity and niceness. Thanks @sandreae.

Btw, Some malkovich malkovich going on here:

```
test src/operation/operation.rs - operation::operation::Operation::new_create (line 226) ... ok
```

**Pull request merged**
