### PR TITLE
Serialize `PublicKey` as bytes

### PR DESCRIPTION
**Pull request by sandreae**
closes: #494 

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header
- [x] Check if descriptions and terminology match `handbook` content (and visa-versa)

### CODE REVIEW

**Comment by adzialocha** [comment]
Interesting issue! I wonder if actually serializing to a string is the thing we want to do ..

The steps (I think) are currently like that:

1. Have a `PublicKey` which is a wrapper type around the `ed25519-dalek` struct equivalent, this one serializes to bytes
2. Convert it to string representation for serialization, by encoding bytes as hex string, now the size doubles (64 bytes)
3. Encode it as CBOR, which will be a CBOR string

But what we want:

1. Same as above
2. Serialize it as bytes (still 32 bytes)
3. Encode it as CBOR, still bytes

IF we want a human readable representation of the CBOR bytes, we can always still encode it as a hex string afterwards, but the machine representation it doesn't matter (and we save bandwith).

**Comment by adzialocha** [comment]
The issue here is that we Serialize already as in the second scenario above (32 bytes), but the Deserializer is wrong ..

**Comment by adzialocha** [comment]
Here is an example on how this can be automatically done depending on if the underlying encode is human readable or not: https://github.com/p2panda/p2panda/blob/679107b636eea39e7713d9b21ac69df28aaad97d/p2panda-rs/src/entry/encoded_entry.rs#L26

**Comment by sandreae** [comment]
Fixing `Deserialize` so it's expecting bytes sounds good to me 👍

**Comment by sandreae** [comment]
@adzialocha how is this looking to you? Not sure I totally understood the best way to use the existing helper methods....

**Comment by adzialocha** [comment]
> @adzialocha how is this looking to you? Not sure I totally understood the best way to use the existing helper methods....

You're serializing to hex which still doubles the byte size, for CBOR it's enough to just encode the bytes directly from the public key (and vice versa for decoding).

Check out the example I commented earlier on, we should have methods which only serialize to hex if it's a human readable encoding (for example JSON).

**Comment by sandreae** [comment]
> 
@adzialocha how is this looking to you? Not sure I totally understood the best way to use the existing helper methods....

You're serializing to hex which still doubles the byte size, for CBOR it's enough to just encode the bytes directly from the public key (and vice versa for decoding).

Check out the example I commented earlier on, we should have methods which only serialize to hex if it's a human readable encoding (for example JSON).

I actually thought this is what the methods i used were doing. This one for example: https://github.com/p2panda/p2panda/blob/4dd6d8e199d9451951d1e9d454e80cb1be9b1fc1/p2panda-rs/src/serde/hex_str.rs#L5-L16

**Comment by adzialocha** [comment]
Ah ja, this works as well. You can use the derive macros for that:

```
    #[serde(serialize_with = "serialize_hex", deserialize_with = "deserialize_hex")] Vec<u8>,
```

**Comment by sandreae** [comment]
> 

Ooookay, cool. But this didn't work when I tried it in this commit https://github.com/p2panda/p2panda/pull/495/commits/a0d3205cafc2277c259c94ae2fa0b651bd532676 and you also thought it wasn't correct. Is that because I used the methods in manual implementations of `Serialize` and `Deserialize`? I didn't think that would make a difference...

**Comment by adzialocha** [comment]
> > 
> 
> Ooookay, cool. But this didn't work when I tried it in this commit https://github.com/p2panda/p2panda/pull/495/commits/a0d3205cafc2277c259c94ae2fa0b651bd532676 and you also thought it wasn't correct. Is that because I used the methods in manual implementations of `Serialize` and `Deserialize`? I didn't think that would make a difference...

Ah sorry, I think I didn't look closely and got confused why you didn't just use the derive macros. Then it's all good 👍🏻

**Comment by adzialocha** [comment]
I've reverted everything back to https://github.com/p2panda/p2panda/commit/a0d3205cafc2277c259c94ae2fa0b651bd532676 and will merge now, sorry for the confusion!

**Pull request merged**
